CREATE TABLE dbo.Categorias
(
	   [CategoriaId] INT NOT NULL IDENTITY(1,1) CONSTRAINT PK_Categorias PRIMARY KEY CLUSTERED([CategoriaId])
	 , [Descripcion] VARCHAR(250) NOT NULL
	 ,Estado BIT NOT NULL
)
WITH (DATA_COMPRESSION = PAGE)
GO
